### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by harr1193** [harr1193/MI-449-SS17-741-html-semantic-elements-5BSgA-#1]
@KatieMFritz Can you take a look at this? It's [hosted here](https://harr1193.github.io/MI-449-SS17-741-html-semantic-elements-5BSgA-/) and meets the following criteria:

- [x] Place a `nav` element at the top of the page that includes (fake) links to other pages
- [x] Use the `main` element appropriately
- [x] Include three products your store sells, all listed on the same Products page
- [x] For each product, correctly use an `article`, `header`, and `footer` element
- [x] Use `figure` and `figcaption` to show what each product looks like
- [x] Each product includes a `nav` element with one or more links to related products (the links don't have to go anywhere)
- [x] Use an `aside` in one or more products to advertise a promotion or discount for that product

**Comment by KatieMFritz** [comment]
Oh come on, now I'm hungry! 😝 

Nice job on this. You've used all the elements appropriately! You didn't quite meet the requirement to include a `nav` for _each_ `article`, but it seems like you understand how to do it?

There are some HTML errors though. Please check your hosted site on the [W3 Validator](https://validator.w3.org/nu/?doc=https%3A%2F%2Fharr1193.github.io%2FMI-449-SS17-741-html-semantic-elements-5BSgA-%2F), fix all the errors (warnings are okay, as long as you understand why they're happening), and resubmit. :smile:

Tip for prototyping: When you want to make a link that doesn't go anywhere, you can use `<a href="#">`. It will just reload the page if the user clicks on it, so you don't get redirected away from your project, but it's a real link so you get real link styles and behaviors, which is useful when you're prototyping. You don't have to change the Google links you included here - just wanted you to know! 💡

**Comment by harr1193** [comment]
Changes were fixed

**Comment by KatieMFritz** [comment]
Nice! 😄  🍞 🧀 

:shipit:
